


server:
  port: 8080

external-apis:
  users:
    urls:
      host: http://localhost:8070
      paths:
        getUsers: "/api/getUsers"
        getUserById: "/api/getUserById"
        getUsersByRole: "/api/getUsersByRole"
        addUser: "/api/addUser"
        updateUser: "/api/updateUser"
        deleteUser: "/api/deleteUser"
        getUserByEmail: "/api/getUserByEmail"
